Fix build of cel-cpp with newer clang versions
Specifically I'm using clang-18 and with it I get a few errors like
this coming from json.h:

```
In file included from external/com_google_cel_cpp/runtime/standard/comparison_functions.cc:15:
In file included from external/com_google_cel_cpp/runtime/standard/comparison_functions.h:18:
In file included from external/com_google_absl/absl/status/status.h:56:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/ostream:40:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/ios:41:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/exception:164:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/exception_ptr.h:41:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/move.h:37:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/type_traits:1326:23: error: incomplete type 'cel::JsonObject' used in type trait expression
 1326 |                     __bool_constant<__has_trivial_destructor(_Tp)>>::type
      |                                     ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/type_traits:3297:5: note: in instantiation of template class 'std::is_trivially_destructible<cel::JsonObject>' requested here
 3297 |     is_trivially_destructible<_Tp>::value;
      |     ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/variant:340:5: note: in instantiation of variable template specialization 'std::is_trivially_destructible_v<cel::JsonObject>' requested here
  340 |           (is_trivially_destructible_v<_Types> && ...);
      |            ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/variant:349:4: note: in instantiation of static data member 'std::__detail::__variant::_Traits<cel::JsonNull, bool, double, absl::Cord, cel::JsonArray, cel::JsonObject>::_S_trivial_dtor' requested here
  349 |           _S_trivial_dtor && _S_trivial_move_ctor
      |           ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/variant:731:45: note: in instantiation of static data member 'std::__detail::__variant::_Traits<cel::JsonNull, bool, double, absl::Cord, cel::JsonArray, cel::JsonObject>::_S_trivial_move_assign' requested here
  731 |       _Move_assign_base<_Traits<_Types...>::_S_trivial_move_assign, _Types...>;
      |                                             ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/variant:734:28: note: in instantiation of template type alias '_Move_assign_alias' requested here
  734 |     struct _Variant_base : _Move_assign_alias<_Types...>
      |                            ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/variant:1338:15: note: in instantiation of template class 'std::__detail::__variant::_Variant_base<cel::JsonNull, bool, double, absl::Cord, cel::JsonArray, cel::JsonObject>' requested here
 1338 |     : private __detail::__variant::_Variant_base<_Types...>,
      |               ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/stl_vector.h:1086:24: note: in instantiation of template class 'std::variant<cel::JsonNull, bool, double, absl::Cord, cel::JsonArray, cel::JsonObject>' requested here
 1086 |       { return begin() == end(); }
      |                        ^
external/com_google_cel_cpp/common/json.h:126:43: note: in instantiation of member function 'std::vector<std::variant<cel::JsonNull, bool, double, absl::Cord, cel::JsonArray, cel::JsonObject>>::empty' requested here
  126 |   bool empty() const { return impl_.get().empty(); }
      |                                           ^
external/com_google_cel_cpp/common/json.h:73:34: note: forward declaration of 'cel::JsonObject'
   73 | class ABSL_ATTRIBUTE_TRIVIAL_ABI JsonObject;
```

This is just an example, there are more errors, but all of them are similar to each other.
And all of them have the same root cause. Basically there is a circular dependencies between
Json, JsonArray and JsonObject types. This circular dependency by itsels if not a problem (and
certainly wasn't the problem before with older versions of clang and standard libraries,
libstdc++ in our case) and is dealt with in the code by making forward declarations of the classes
when necessary.

However, apparently now somewhere deep in the implementation of std::variant we have calls to C++
type traits that require a fully defined types (specifically in the error above
is_trivially_destructible requires a fully defined type). So when compiler is forced to instantiate
parts of std::variant template that refer to type traits, it results in a compilation error if at
that point in time compiler only saw a forward declration of the type and not the complete defintiion.

NOTE: It's not a mistake that type traits require a fully defined type - C++ standard is pretty
clear on that point; what is not clear is why those type traits calls were added in the first
place.

The problem shown above arieses specifically when compiler sees a definiontion of JsonArray::empty
method that calls std::vector<std::variant>::empty which forces C++ compiler to instantiate the
type and results in an error.

The solutions is rather simple and non-invasive - move the defitnions of the methods out of the class
to the point where all the class definitions are already available to the compiler. I can also see
it being done for at least some of the methods already, so it should not be that big of a deal to
move a few other methods outside of the class as well.

Plus, I would imagine sooner or later cel C++ implementation will need to support newer versions of
clang compiler, so hopefully this change will not be terribly disruptive and align with inevitable
future of supporting newer compiler versions.

Signed-off-by: Mikhail Krinkin <krinkin.m.u@gmail.com>